#!/bin/bash

[[ -z "$1" ]] && { echo "Usage: $0 <profile>"; exit 1; } || profile=$1

grep -A2 ${profile} ~/.aws/credentials | grep -v ${profile} \
| awk '{printf "export %s=%s\n",toupper($1),$3}' > ~/.aws.env.${profile}
